### ISSUE TITLE
Sidebar collapse open on same side as sidebar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#1045]
Sidebar is on right but trigger opens canvas on left. I wonder if we can simply change the CSS to have it appear in from right

**Comment by LukasWieditz** [comment]
Could/should we also support swipe show? Swipe right for navigation, swipe left for sidebar on mobile.

**Comment by Ian-Hitt** [comment]
Capturing swipe gesture support on web is still not super duper afaik. @kylerc can decide on that one.

**Comment by mikecreuzer** [comment]
As far as I know, swipe is in the standard API for web frameworks like Webkit/Blink so should be safe. I think a SP for it but I like the idea indeed.

**Comment by kylerc** [comment]
Yeah swipe wise it'd be nice if it was simpler but on ios at least edge swipes are reserved by the browser itself for forward and back navigation.  I don't think android reserves these so maybe could use them on android if we think users would use them very often.  We likely wouldn't want to capture swipes on the body itself since that would probably start to conflict with things like Reactions gestures but maybe would capture them on just the sticky bars (for iOS as long as they don't start near the edge of the screen)?  I don't think there's a good built in option for this, but third party libraries like http://hammerjs.github.io/recognizer-swipe/ could work I suppose.

**Comment by Ian-Hitt** [comment]
Moving swipe support to new issue: https://github.com/Audentio/xf2theme-issues/issues/1086
