### ISSUE TITLE
UIX Dark - Link Hover Color Oddity

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#1050]
Style Name: UI.X Dark

Style Version: 2.1

UI.X Add-on Version: Latest

XenForo Version: 2.1.0

Operating System (and Version): Windows 10 / 64-Bit (Latest Stable)

Browser Name (and Version): Chrome 72 / 64-Bit (Latest Stable)

Does this issue happen in the default XenForo style? Nope.

Summary of issue: When hovering over a link in the header/navbar, you'll have to be quick but you'll notice that link text such as "Bookmarks" shifts color in an odd way. This does not happen in default. Its like its quickly trying to override something in the code to eventually display properly. You'll notice in the screen capture video that in both the upper right side links and the nav links it very quickly shifts from a darker blue up to a lighter blue (and in my custom offshoot for wtf.com as well in red).

Upload any screenshots related to the issue below

![uix-dark-hover-over-link-color-oddity](https://user-images.githubusercontent.com/35111972/53198682-faed8400-35ea-11e9-9c5a-b6aea628bdbc.gif)

**Comment by lilalien** [comment]
I can still reproduce this every time on the latest UI.X dark update as of this posting.

**Comment by daltonp** [comment]
I am able to replicate this on my demo as well.

**Comment by Ian-Hitt** [comment]
Appears to be a render bug only in Windows machines. Does *not* happen with inspector open. Also does not happen when using medium sized avatar so far as I can tell.

**Comment by Ian-Hitt** [comment]
This bug happens when the browser switches from CPU rendering to GPU rendering for things like opacity and transform transitions. It is not a code bug, nor a render bug, and cannot be helped by anything other than using less of those css properties in general. 

The closest potential fix would be to add `backface-visibility: hidden;`, however this has performance implications and should be used sparingly.
