### ISSUE TITLE
Add swipe support for canvases

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#1086]
http://www.netcu.de/jquery-touchwipe-iphone-ipad-library

**Comment by Ian-Hitt** [comment]
@kylerc this doesn't work for me on iOs, android, and also intentionally doesn't support mouse drag as swipe event

**Comment by kylerc** [comment]
After looking into this a little more, most libraries seem to be either fairly large which would hurt our performance goals and/or have a large number of users complaining about how well they actually work.  Since there isn't (yet) a good way to do this natively in browsers can probably close this for now and revisit if browsers add a good first-party way to recognize this.
