### ISSUE TITLE
Sticky sidebar (UI.X Pro)

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#1089]
So when scrolling down, the sidebar would stick at the very top before yesterday's update. Now it's mid way and cut off as seen in screenshot:
![sidebar](https://user-images.githubusercontent.com/43339306/57029816-c1647500-6c3a-11e9-8816-98d481828336.png)

**Comment by joyfreak** [comment]
When scrolling up it seems to be fine, sticks at very top
![scroll up](https://user-images.githubusercontent.com/43339306/57029863-de994380-6c3a-11e9-9942-8f8855f7fcbc.png)

**Comment by Ian-Hitt** [comment]
The sidebar when scrolling down is intentionally sticky at the bottom of the screen, not at the top. This is ideal because it allows you to scroll past all the sidebar content so users can see all of the widget content. This has been a feature for the past few releases, not just this one. You can revert to the original stick top only setting in Style Properties > Sidebar.
