### ISSUE TITLE
[UIX Pro] - Add option for make a sticky user cell

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1107]
Example:

![xtr-sticky_postbit](https://user-images.githubusercontent.com/6899856/58034433-dee47a80-7b26-11e9-8603-38b583d5bca5.gif)

**Comment by Ian-Hitt** [comment]
This feature request seems to situational in that you would _only_ want it when you have a very large post. Otherwise it is disruptive in that is is activating the top item on the screen when the user is more likely to be reading one of the other various posts instead. This is also fairly ease CSS to add to a custom project and I think is better than adding it to the core.
