### ISSUE TITLE
We need a proper solution for when content moves responsively

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#169]

**Comment by kylerc** [comment]
This specifically happens in Section Links currently at the responsive width for the section links to go to the sidebar if there is no other content vs if there is other content.  This could also be an issue in some specific configurations of staffbar content.  Ideally we would have a responsive breakpoint for all content individually and then find the minimum breakpoint for content inside the bar.  Below that point we hide the whole bar since there is no longer content.
