### ISSUE TITLE
Some options can cause misplaced navbar tabs

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#221]
Disable the logo block and navigation tab icons.

![tab_issue](https://user-images.githubusercontent.com/26636634/33186495-eebbdefe-d081-11e7-84aa-3fca92133a98.png)

**Comment by Ian-Hitt** [comment]
@nsaneman They are not misplaced, but rather everything is centered. This creates a problem with you have a background color for active tabs, the tab is not the tallest component, and you want them to be aligned to the bottom. The solution here would be to make the navtabs the same height as the sticky navigation bar. Otherwise, it limits other design styles.
