### ISSUE TITLE
UI.X - Choice of Postbit extras horizontal layout

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#492]
Style Name: UI.X

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Suggestion: I would like to see an option to display icons and values horizontally.. You'll see the different in the screenshot... If someone only displays a few things, it looks great horizontally. If they have a lot, then it can make sense vertically. I think an option would look great for this.

![postbit_extras_alternate_layout_screenshot-original](https://user-images.githubusercontent.com/35111972/36750107-b1fd5724-1bca-11e8-9c8d-fcb0ec519b4d.png)
![postbit_extras_alternate_layout_screenshot](https://user-images.githubusercontent.com/35111972/36750108-b212177c-1bca-11e8-90f5-96b7f64ce302.png)

**Comment by Ian-Hitt** [comment]
@lilalien This does look good in theory, but the issue is that all items must remain roughly equal in mass, or it breaks down fairly quickly. See the screenshot I posted of what this would look like "out of the box."

<img width="253" alt="screen shot 2018-05-10 at 3 10 51 pm" src="https://user-images.githubusercontent.com/15836384/39891925-908ffe02-5464-11e8-9ffa-4f58ae5eb5ff.png">

I do visually like this when when it's guaranteed that items will be equal in mass, but a bit too easy to break for a supported Style Property. It is a fairly easy customization to make, so I think it is best to leave at that.
