### ISSUE TITLE
Flashing shown above navigation bar

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#558]
![flashingbar](https://user-images.githubusercontent.com/32306910/39193143-7ca04d0a-47a0-11e8-9a09-d0d99352f3a4.gif)
This can be seen on all of our themes, just navigate to a forum thread before pressing enter into the reply box. Look above the sticky navigation as you should see the flashing there.

**Comment by kylerc** [comment]
Unfortunately, this is due to the implementation details of StickyKit which XF is including for sticky functionality.  XF's default style isn't using this specific part of stickykit since the have a simpler sticky setup so this doesn't happen on the default style, but the flicker is built into how stickykit handles resizes in some situations sadly.  Will require #571

**Comment by mikecreuzer** [comment]
As we wont be touching sticky kit unless XenForo changes, closing
