### ISSUE TITLE
shadow for overflow tabs when bar has no bg color

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#565]
<img width="255" alt="screen shot 2018-04-24 at 10 14 18 am" src="https://user-images.githubusercontent.com/1217271/39196663-4bcd4342-47a8-11e8-95dc-56cb29321338.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer its missing a shadow because it has no bg color to blend into.

intended:
<img width="896" alt="screen shot 2018-04-24 at 11 15 02 am" src="https://user-images.githubusercontent.com/15836384/39200095-c35e8274-47b0-11e8-8a25-a1e4bf9001d9.png">

with no bg color:

<img width="788" alt="screen shot 2018-04-24 at 11 14 49 am" src="https://user-images.githubusercontent.com/15836384/39200100-c88ce79a-47b0-11e8-8b8f-8d32274af6a8.png">


any suggetsions?

**Comment by mikecreuzer** [comment]
Point being it looks broken so we can try a few things. Nav trigger bg, css tweaks via sticky state selector, etc
