### ISSUE TITLE
Search (position: tablinks right) doesn't appear until you click in the area

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2theme-issues#57]
So if you have the search position as "tablinks (right)", the search wont appear until you click in the area.

http://imgur.com/gallery/tRw7j

**Comment by Ian-Hitt** [comment]
Hmm, not entirely sure that this is a bug. The issue is just that the background color is rgba(255,255,255,.2). Solutions would be either forcing a new background color when search is in tablinks (which would overwrite the style property, and be bad for dark themes), or just require people to set a new background color for search. Generally I lean towards not overwriting style properties with hard coded values, so im going to say its not a bug, just user error.
