### ISSUE TITLE
Topic 'state' moved to filter bar and filter bar creating for 'golden routes'

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#669]
- [ ] Add filter bar to latest posts
- [ ] Add filter bar to trending
- [ ] (?) Add filter bar to (any other routes we want like top/latest threads?)

I think these are JS, but keeping one issue for now:

- [ ] Based on URI/or state changes, add list of active topics to the filter bar
- [ ] 'x' icon for clear (ALL filters OR just topics?)
- [ ] unchecking them on filter, unchecks them everywhere, keeps state

**Comment by kylerc** [comment]
@LukasWieditz can you pass in the correct parameters to the `thtopics_filterbar_topics.html` template I made.  I should have a template mod to apply this to the `forum_new_posts` template filterbar but I think it needs a code event (maybe?) to get the list of topics into it.  I haven't tested it beyond that point, but once the data is there let me know.  I made some changes to try and get that working but I'm guessing there will be some small changes since it's not tested with real data yet.
